letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
       | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p"
       | "q" | "r" | "s" | "t" | "u" | "v" | "w"
       | "x" | "y" | "z" ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
symbol = "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">"
       | "'" | '"' | "=" | "|" | "." | "," | ";" | "-"  | "_"
       | "+" | "*" | "?" | "\n" | "\t" | "\r" | "\f" | "\b" ;
character = letter | digit | symbol | " " ;

number = [ "-" ], digit, { digit }, [ ".", digit + ] ;
string = '"', { character }, '"' ;
identifier = letter | "_", { letter | digit | "_" | "-" } ;
boolean = "true" | "false" ;
null = "null" ;

program = { declaration }, EOF ;
declaration = statement | variable-declaration ;

statement = expression, ";" ;
variable-declaration = "var", identifier, ( "=", expression ) ?, ";" ;

expression = equality | ternary ;
ternary    = expression, "?", expression, ":", expression ;
equality   = comparison, { ( "!=" | "==" ), comparison } ;
comparison = term, { ( ">" | "<" | ">=" | "<=" ), term } ;
term       = factor, { ( "+" | "-" ), factor } ;
factor     = unary, { ( "/" | "*" ), unary } ;  (* make it left recursive? *)
unary      = ( "!" | "-" ), unary | primary ;
primary    = number | string | boolean | null | ( "(", expression, ")" ) | identifier ;


